// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Thomas.TechTest.Data;

namespace Thomas.TechTest.Data.Migrations
{
    [DbContext(typeof(CandidateDbContext))]
    [Migration("20200325214717_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2");

            modelBuilder.Entity("Thomas.TechTest.Data.AptitudeAssessment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CompletedOn")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SentOn")
                        .HasColumnType("TEXT");

                    b.Property<int?>("TrainabilityIndex")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("AptitudeAssessments");
                });

            modelBuilder.Entity("Thomas.TechTest.Data.BehaviourAssessment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CompletedOn")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SentOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkingStrengths")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("BehaviourAssessments");
                });

            modelBuilder.Entity("Thomas.TechTest.Data.Candidate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("AptitudeAssessmentId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("BehaviourAssessmentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Firstname")
                        .HasColumnType("TEXT");

                    b.Property<string>("Lastname")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AptitudeAssessmentId");

                    b.HasIndex("BehaviourAssessmentId");

                    b.ToTable("Candidates");
                });

            modelBuilder.Entity("Thomas.TechTest.Data.Candidate", b =>
                {
                    b.HasOne("Thomas.TechTest.Data.AptitudeAssessment", "AptitudeAssessment")
                        .WithMany()
                        .HasForeignKey("AptitudeAssessmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Thomas.TechTest.Data.BehaviourAssessment", "BehaviourAssessment")
                        .WithMany()
                        .HasForeignKey("BehaviourAssessmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
